// Configuration file for ESLint (https://eslint.org/)

import { defineConfig } from "eslint/config";
import regexp from "eslint-plugin-regexp";
import test from "eslint-node-test";

export default defineConfig([
	{
		name: "Regular Expressions",
		files: ["**/*.js"],
		plugins: { regexp },
		rules: {
			"regexp/confusing-quantifier": ["error"],
			"regexp/control-character-escape": ["error"],
			"regexp/grapheme-string-literal": ["error"],
			"regexp/hexadecimal-escape": ["error", "never"],
			"regexp/letter-case": ["error"],
			"regexp/match-any": [
				"error",
				{
					allows: ["[^]", "dotAll"],
				},
			],
			"regexp/negation": ["error"],
			"regexp/no-contradiction-with-assertion": ["error"],
			"regexp/no-control-character": ["error"],
			"regexp/no-dupe-characters-character-class": ["error"],
			"regexp/no-dupe-disjunctions": ["error"],
			"regexp/no-empty-alternative": ["error"],
			"regexp/no-empty-capturing-group": ["error"],
			"regexp/no-empty-character-class": ["error"],
			"regexp/no-empty-group": ["error"],
			"regexp/no-empty-lookarounds-assertion": ["error"],
			"regexp/no-empty-string-literal": ["error"],
			"regexp/no-escape-backspace": ["error"],
			"regexp/no-extra-lookaround-assertions": ["error"],
			"regexp/no-invalid-regexp": ["error"],
			"regexp/no-invisible-character": ["error"],
			"regexp/no-lazy-ends": ["error"],
			"regexp/no-legacy-features": ["error"],
			"regexp/no-misleading-capturing-group": ["error"],
			"regexp/no-misleading-unicode-character": ["error"],
			"regexp/no-missing-g-flag": ["error"],
			"regexp/no-non-standard-flag": ["error"],
			"regexp/no-obscure-range": ["error"],
			"regexp/no-octal": ["error"],
			"regexp/no-optional-assertion": ["error"],
			"regexp/no-potentially-useless-backreference": ["error"],
			"regexp/no-standalone-backslash": ["error"],
			"regexp/no-super-linear-backtracking": ["error"],
			"regexp/no-super-linear-move": ["error"],
			"regexp/no-trivially-nested-assertion": ["error"],
			"regexp/no-trivially-nested-quantifier": ["error"],
			"regexp/no-unused-capturing-group": ["error"],
			"regexp/no-useless-assertions": ["error"],
			"regexp/no-useless-backreference": ["error"],
			"regexp/no-useless-character-class": ["error"],
			"regexp/no-useless-dollar-replacements": ["error"],
			"regexp/no-useless-escape": ["error"],
			"regexp/no-useless-flag": ["error"],
			"regexp/no-useless-lazy": ["error"],
			"regexp/no-useless-non-capturing-group": ["error"],
			"regexp/no-useless-quantifier": ["error"],
			"regexp/no-useless-range": ["error"],
			"regexp/no-useless-set-operand": ["error"],
			"regexp/no-useless-string-literal": ["error"],
			"regexp/no-useless-two-nums-quantifier": ["error"],
			"regexp/no-zero-quantifier": ["error"],
			"regexp/optimal-lookaround-quantifier": ["error"],
			"regexp/optimal-quantifier-concatenation": ["error"],
			"regexp/prefer-character-class": ["error"],
			"regexp/prefer-d": ["error"],
			"regexp/prefer-escape-replacement-dollar-char": ["error"],
			"regexp/prefer-lookaround": ["error"],
			"regexp/prefer-named-backreference": ["error"],
			"regexp/prefer-named-capture-group": ["off"],
			"regexp/prefer-named-replacement": ["error"],
			"regexp/prefer-plus-quantifier": ["error"],
			"regexp/prefer-predefined-assertion": ["error"],
			"regexp/prefer-quantifier": ["error"],
			"regexp/prefer-question-quantifier": ["error"],
			"regexp/prefer-range": ["error"],
			"regexp/prefer-regexp-exec": ["error"],
			"regexp/prefer-regexp-test": ["error"],
			"regexp/prefer-result-array-groups": ["error"],
			"regexp/prefer-set-operation": ["error"],
			"regexp/prefer-star-quantifier": ["error"],
			"regexp/prefer-unicode-codepoint-escapes": ["error"],
			"regexp/prefer-w": ["error"],
			"regexp/require-unicode-regexp": ["off"],
			"regexp/require-unicode-sets-regexp": ["off"],
			"regexp/simplify-set-operations": ["error"],
			"regexp/sort-alternatives": ["error"],
			"regexp/sort-character-class-elements": ["error"],
			"regexp/sort-flags": ["error"],
			"regexp/strict": ["error"],
			"regexp/unicode-escape": ["error", "unicodeEscape"],
			"regexp/unicode-property": ["error"],
			"regexp/use-ignore-case": ["error"],
		},
	},
	{
		name: "Tests",
		files: ["**/*.test.js"],
		plugins: { test },
		rules: {
			"test/assertion-arguments": ["error"],
			"test/consistent-assert-style": ["error"],
			"test/consistent-assert-throws-callback-style": ["error"],
			"test/consistent-modifier-style": ["error"],
			"test/consistent-test-context-name": ["error"],
			"test/consistent-test-filename": ["error"],
			"test/consistent-test-it": ["error"],
			"test/hooks-order": ["error"],
			"test/max-assertions": ["error"],
			"test/max-nested-describe": ["error"],
			"test/no-assert-in-describe": ["error"],
			"test/no-assert-in-hook": ["error"],
			"test/no-assert-match-string": ["error"],
			"test/no-assert-throws-async": ["error"],
			"test/no-assert-throws-call": ["error"],
			"test/no-assert-throws-multiple-statements": ["error"],
			"test/no-assert-throws-string": ["error"],
			"test/no-async-describe": ["error"],
			"test/no-async-fn-without-await": ["error"],
			"test/no-callback-and-promise": ["error"],
			"test/no-commented-tests": ["error"],
			"test/no-compound-assertion": ["error"],
			"test/no-conditional-assertion": ["error"],
			"test/no-conditional-in-test": ["error"],
			"test/no-conditional-tests": ["error"],
			"test/no-conflicting-modifiers": ["error"],
			"test/no-constant-assertion": ["error"],
			"test/no-done-callback": ["error"],
			"test/no-duplicate-assertions": ["error"],
			"test/no-duplicate-hooks": ["error"],
			"test/no-duplicate-mock-timers-enable": ["error"],
			"test/no-duplicate-plan": ["error"],
			"test/no-expect-failure-without-reason": ["error"],
			"test/no-export": ["error"],
			"test/no-identical-assertion-arguments": ["error"],
			"test/no-identical-title": ["error"],
			"test/no-import-test-files": ["error"],
			"test/no-incorrect-deep-equal": ["error"],
			"test/no-incorrect-strict-equal": ["error"],
			"test/no-late-test-activity": ["error"],
			"test/no-loop-static-title": ["error"],
			"test/no-misused-concurrency": ["error"],
			"test/no-misused-context-hook": ["error"],
			"test/no-mock-timers-destructured-import": ["error"],
			"test/no-mock-module-after-import": ["error"],
			"test/no-nested-tests": ["error"],
			"test/no-only-test": ["error"],
			"test/no-parent-test-context": ["error"],
			"test/no-process-chdir-in-test": ["error"],
			"test/no-process-env-mutation": ["error"],
			"test/no-process-exit-in-test": ["error"],
			"test/no-skip-test": ["error"],
			"test/no-skip-without-reason": ["error"],
			"test/no-skip-without-return": ["error"],
			"test/no-sleep-in-test": ["error"],
			"test/no-snapshot-in-loop": ["error"],
			"test/no-standalone-assert": ["error"],
			"test/no-test-global-configuration": ["error"],
			"test/no-test-inside-hook": ["error"],
			"test/no-test-return-statement": ["error"],
			"test/no-todo-test": ["error"],
			"test/no-unawaited-promise-assertion": ["error"],
			"test/no-unawaited-rejects": ["error"],
			"test/no-unawaited-subtest": ["error"],
			"test/no-unknown-test-options": ["error"],
			"test/no-unneeded-async-rejects-callback": ["error"],
			"test/no-useless-assertion": ["error"],
			"test/prefer-assert-match": ["error"],
			"test/prefer-assert-throws": ["error"],
			"test/prefer-async-await": ["error"],
			"test/prefer-context-mock": ["error"],
			"test/prefer-diagnostic": ["error"],
			"test/prefer-equality-assertion": ["error"],
			"test/prefer-hooks-on-top": ["error"],
			"test/prefer-lowercase-title": ["error"],
			"test/prefer-mock-accessor": ["error"],
			"test/prefer-mock-call-count": ["error"],
			"test/prefer-mock-method": ["error"],
			"test/prefer-strict-assert": ["error"],
			"test/prefer-test-context-assert": ["error"],
			"test/prefer-todo": ["error"],
			"test/require-assertion": ["error"],
			"test/require-await-concurrent-subtests": ["error"],
			"test/require-context-assert-with-plan": ["error"],
			"test/require-hook": ["error"],
			"test/require-mock-timers-advance": ["error"],
			"test/require-mock-timers-apis": ["error"],
			"test/require-throws-expectation": ["error"],
			"test/require-throws-validator-return-true": ["error"],
			"test/require-top-level-describe": ["off"],
			"test/test-title": ["error"],
			"test/test-title-format": ["error"],
			"test/valid-describe-callback": ["error"],
			"test/valid-test-tags": ["error"],
		},
	},
]);
