// Configuration file for ESLint (https://eslint.org/)

import { defineConfig } from "eslint/config";
import test from "eslint-node-test";

export default defineConfig([
	{
		files: ["**/*.test.js"],
		plugins: { test },
		rules: {
			"test/assertion-arguments": ["error"],
			"test/consistent-assert-style": ["error"],
			"test/consistent-assert-throws-callback-style": ["error"],
			"test/consistent-modifier-style": ["error"],
			"test/consistent-test-context-name": ["error"],
			"test/consistent-test-filename": ["error"],
			"test/consistent-test-it": ["error"],
			"test/hooks-order": ["error"],
			"test/max-assertions": ["error"],
			"test/max-nested-describe": ["error"],
			"test/no-assert-in-describe": ["error"],
			"test/no-assert-in-hook": ["error"],
			"test/no-assert-match-string": ["error"],
			"test/no-assert-throws-async": ["error"],
			"test/no-assert-throws-call": ["error"],
			"test/no-assert-throws-multiple-statements": ["error"],
			"test/no-assert-throws-string": ["error"],
			"test/no-async-describe": ["error"],
			"test/no-async-fn-without-await": ["error"],
			"test/no-callback-and-promise": ["error"],
			"test/no-commented-tests": ["error"],
			"test/no-compound-assertion": ["error"],
			"test/no-conditional-assertion": ["error"],
			"test/no-conditional-in-test": ["error"],
			"test/no-conditional-tests": ["error"],
			"test/no-conflicting-modifiers": ["error"],
			"test/no-constant-assertion": ["error"],
			"test/no-done-callback": ["error"],
			"test/no-duplicate-assertions": ["error"],
			"test/no-duplicate-hooks": ["error"],
			"test/no-duplicate-plan": ["error"],
			"test/no-export": ["error"],
			"test/no-identical-assertion-arguments": ["error"],
			"test/no-identical-title": ["error"],
			"test/no-incorrect-deep-equal": ["error"],
			"test/no-incorrect-strict-equal": ["error"],
			"test/no-loop-static-title": ["error"],
			"test/no-misused-concurrency": ["error"],
			"test/no-mock-timers-destructured-import": ["error"],
			"test/no-nested-tests": ["error"],
			"test/no-only-test": ["error"],
			"test/no-parent-test-context": ["error"],
			"test/no-process-env-mutation": ["error"],
			"test/no-process-exit-in-test": ["error"],
			"test/no-skip-test": ["error"],
			"test/no-skip-without-reason": ["error"],
			"test/no-skip-without-return": ["error"],
			"test/no-sleep-in-test": ["error"],
			"test/no-snapshot-in-loop": ["error"],
			"test/no-standalone-assert": ["error"],
			"test/no-test-inside-hook": ["error"],
			"test/no-test-return-statement": ["error"],
			"test/no-todo-test": ["error"],
			"test/no-unawaited-promise-assertion": ["error"],
			"test/no-unawaited-rejects": ["error"],
			"test/no-unawaited-subtest": ["error"],
			"test/no-unknown-test-options": ["error"],
			"test/no-useless-assertion": ["error"],
			"test/prefer-assert-match": ["error"],
			"test/prefer-assert-throws": ["error"],
			"test/prefer-async-await": ["error"],
			"test/prefer-context-mock": ["error"],
			"test/prefer-diagnostic": ["error"],
			"test/prefer-equality-assertion": ["error"],
			"test/prefer-hooks-on-top": ["error"],
			"test/prefer-lowercase-title": ["error"],
			"test/prefer-mock-method": ["error"],
			"test/prefer-strict-assert": ["error"],
			"test/prefer-test-context-assert": ["error"],
			"test/prefer-todo": ["error"],
			"test/require-assertion": ["error"],
			"test/require-await-concurrent-subtests": ["error"],
			"test/require-context-assert-with-plan": ["error"],
			"test/require-hook": ["error"],
			"test/require-mock-timers-advance": ["error"],
			"test/require-mock-timers-apis": ["error"],
			"test/require-throws-expectation": ["error"],
			"test/require-throws-validator-return-true": ["error"],
			"test/require-top-level-describe": ["off"],
			"test/test-title": ["error"],
			"test/test-title-format": ["error"],
			"test/valid-describe-callback": ["error"],
		},
	},
]);
