# Configuration file for Gitlab CI/CD (https://docs.gitlab.com/ci/)

stages:
  - test
  - publish

default:
  cache: &npm_cache
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

variables:
  NODE: 26.0.0

verify:
  stage: test
  image: node:${NODE}
  cache:
    <<: *npm_cache
  script:
    - npm clean-install
    - npm run verify
    - npm run mutation
    - npm run dogfeed
node24:
  stage: test
  image: node:24.0.0
  needs:
    - verify
  cache:
    <<: *npm_cache
  script:
    - npm clean-install
    - npm run test
publish:
  stage: publish
  image: node:${NODE}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  id_tokens:
    NPM_ID_TOKEN:
      aud: npm:registry.npmjs.org
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - npm clean-install
    - npm run package
    - npm publish || true
