name: Feature Request
description: Request a new feature.
labels:
  - enhancement
body:
  - id: pre-check
    type: checkboxes
    attributes:
      label: Pre-check
      description: |
        Before you submit your report, make sure the features has not already
        been requested. Also check for closed feature requests, e.g. in case it
        has been fixed in a new version.
      options:
        - label: I have searched the existing issues
          required: true
  - id: related
    type: textarea
    attributes:
      label: Related
      description: |
        List any related items, describe the relation.
    validations:
      required: false
  - id: version
    type: textarea
    attributes:
      label: Version information
      description: |
        Run `strip-comments-js --version` or `npm ls strip-comments-js` and
        paste the result below.
      placeholder: |
        strip-comments-js : v1.2.0
        Node.js           : v26.4.0

        OR

        `-- strip-comments-js@1.2.0
    validations:
      required: true
  - id: summary
    type: textarea
    attributes:
      label: Summary
      description: |
        Provide a short description of the feature.
    validations:
      required: true
  - id: interface
    type: textarea
    attributes:
      label: Interface
      description: |
        Describe how the feature would be used. For example, through a CLI flag
        or API option.
    validations:
      required: true
  - id: example
    type: textarea
    attributes:
      label: Usage example
      description: |
        Provide an example use case where this feature would be useful.
    validations:
      required: true
  - id: open-ended
    type: textarea
    attributes:
      label: Further details
      description: |
        Share any additional information you think is relevant.
    validations:
      required: false
